kind: pipeline
name: default

steps:
- name: test 
  image: golang
  commands:
    - go test -parallel 10 --race ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.39
  commands:
    - golangci-lint run

- name: test routine
  image: golang
  commands:
    - cd routine
    - go test -parallel 10 --race ./... 

- name: golangci-lint routine
  image: golangci/golangci-lint:v1.39
  commands:
    - cd routine
    - golangci-lint run
