version: "2"
linters:
  default: all
  disable:
  # deprecated
    - wsl
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - gitoa.ru
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: _example_test\.go
      - linters:
          - exhaustivestruct
          - mnd
          - wrapcheck
        path: _test\.go
      - linters:
          - exhaustivestruct
          - mnd
          - wrapcheck
        path: test/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
